<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\{GalleryAlbum, GalleryItem};
use Carbon\Carbon;

class GallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create sample gallery albums
        $albums = [
            [
                'title' => 'Student Life at Akuru Institute',
                'slug' => 'student-life-akuru-institute',
                'description' => 'A collection of photos showcasing daily life, activities, and learning experiences of our students at Akuru Institute.',
                'cover_image' => 'gallery/student-life-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => true,
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Quran Competition 2024',
                'slug' => 'quran-competition-2024',
                'description' => 'Photos and videos from our annual Quran recitation competition featuring students from all age groups.',
                'cover_image' => 'gallery/quran-competition-cover.jpg',
                'type' => 'mixed',
                'status' => 'published',
                'is_featured' => true,
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'Arabic Language Classes',
                'slug' => 'arabic-language-classes',
                'description' => 'Learning Arabic through interactive classes, group activities, and cultural immersion experiences.',
                'cover_image' => 'gallery/arabic-classes-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => false,
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'Community Events',
                'slug' => 'community-events',
                'description' => 'Photos from various community gatherings, celebrations, and special events at Akuru Institute.',
                'cover_image' => 'gallery/community-events-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => false,
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'Graduation Ceremony 2024',
                'slug' => 'graduation-ceremony-2024',
                'description' => 'Celebrating our graduates and their achievements in Islamic education and Quran memorization.',
                'cover_image' => 'gallery/graduation-2024-cover.jpg',
                'type' => 'mixed',
                'status' => 'published',
                'is_featured' => true,
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Islamic Studies Workshops',
                'slug' => 'islamic-studies-workshops',
                'description' => 'Interactive workshops and seminars covering various aspects of Islamic studies and contemporary issues.',
                'cover_image' => 'gallery/islamic-workshops-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => false,
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'title' => 'Campus Facilities',
                'slug' => 'campus-facilities',
                'description' => 'A tour of our modern facilities including classrooms, library, prayer areas, and recreational spaces.',
                'cover_image' => 'gallery/campus-facilities-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => false,
                'is_public' => true,
                'sort_order' => 7,
            ],
            [
                'title' => 'Teacher Training Programs',
                'slug' => 'teacher-training-programs',
                'description' => 'Professional development sessions and training programs for our teaching staff.',
                'cover_image' => 'gallery/teacher-training-cover.jpg',
                'type' => 'photos',
                'status' => 'published',
                'is_featured' => false,
                'is_public' => true,
                'sort_order' => 8,
            ],
        ];

        $createdAlbums = [];
        foreach ($albums as $album) {
            $createdAlbums[] = GalleryAlbum::create($album);
        }

        // Create sample gallery items for each album
        $galleryItems = [
            // Student Life Album
            [
                'gallery_album_id' => $createdAlbums[0]->id,
                'title' => 'Students in Quran Class',
                'description' => 'Young students engaged in Quran recitation during their regular class session.',
                'file_path' => 'gallery/student-life/students-quran-class.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 245760,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/student-life/thumbnails/students-quran-class.jpg',
                'alt_text' => 'Students learning Quran in classroom',
                'caption' => 'Dedicated students practicing their Quran recitation with their teacher.',
                'tags' => ['students', 'quran', 'classroom', 'learning'],
                'sort_order' => 1,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[0]->id,
                'title' => 'Group Study Session',
                'description' => 'Students working together on their Islamic studies assignments.',
                'file_path' => 'gallery/student-life/group-study.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 198432,
                'dimensions' => ['width' => 1920, 'height' => 1280],
                'thumbnail_path' => 'gallery/student-life/thumbnails/group-study.jpg',
                'alt_text' => 'Students in group study session',
                'caption' => 'Collaborative learning environment where students help each other.',
                'tags' => ['students', 'study', 'group', 'collaboration'],
                'sort_order' => 2,
                'is_featured' => false,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[0]->id,
                'title' => 'Prayer Time',
                'description' => 'Students performing their daily prayers in the institute\'s prayer hall.',
                'file_path' => 'gallery/student-life/prayer-time.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 312456,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/student-life/thumbnails/prayer-time.jpg',
                'alt_text' => 'Students praying in prayer hall',
                'caption' => 'A peaceful moment of worship and reflection.',
                'tags' => ['prayer', 'worship', 'students', 'spiritual'],
                'sort_order' => 3,
                'is_featured' => true,
                'is_public' => true,
            ],

            // Quran Competition Album
            [
                'gallery_album_id' => $createdAlbums[1]->id,
                'title' => 'Competition Opening Ceremony',
                'description' => 'The opening ceremony of our annual Quran competition with all participants.',
                'file_path' => 'gallery/quran-competition/opening-ceremony.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 456789,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/quran-competition/thumbnails/opening-ceremony.jpg',
                'alt_text' => 'Quran competition opening ceremony',
                'caption' => 'Exciting start to our annual Quran recitation competition.',
                'tags' => ['competition', 'quran', 'ceremony', 'opening'],
                'sort_order' => 1,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[1]->id,
                'title' => 'Student Recitation Performance',
                'description' => 'A student delivering a beautiful Quran recitation during the competition.',
                'file_path' => 'gallery/quran-competition/student-recitation.mp4',
                'file_type' => 'video',
                'mime_type' => 'video/mp4',
                'file_size' => 15728640,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/quran-competition/thumbnails/student-recitation.jpg',
                'alt_text' => 'Student reciting Quran in competition',
                'caption' => 'Beautiful recitation showcasing years of dedication and practice.',
                'tags' => ['competition', 'recitation', 'student', 'performance'],
                'sort_order' => 2,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[1]->id,
                'title' => 'Award Ceremony',
                'description' => 'Winners receiving their awards and recognition for their outstanding performance.',
                'file_path' => 'gallery/quran-competition/award-ceremony.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 378912,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/quran-competition/thumbnails/award-ceremony.jpg',
                'alt_text' => 'Award ceremony for Quran competition winners',
                'caption' => 'Celebrating the achievements of our talented students.',
                'tags' => ['awards', 'winners', 'ceremony', 'achievement'],
                'sort_order' => 3,
                'is_featured' => false,
                'is_public' => true,
            ],

            // Arabic Classes Album
            [
                'gallery_album_id' => $createdAlbums[2]->id,
                'title' => 'Arabic Alphabet Learning',
                'description' => 'Students learning the Arabic alphabet through interactive activities.',
                'file_path' => 'gallery/arabic-classes/alphabet-learning.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 234567,
                'dimensions' => ['width' => 1920, 'height' => 1280],
                'thumbnail_path' => 'gallery/arabic-classes/thumbnails/alphabet-learning.jpg',
                'alt_text' => 'Students learning Arabic alphabet',
                'caption' => 'Interactive learning makes Arabic fun and engaging.',
                'tags' => ['arabic', 'alphabet', 'learning', 'interactive'],
                'sort_order' => 1,
                'is_featured' => false,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[2]->id,
                'title' => 'Conversation Practice',
                'description' => 'Students practicing Arabic conversation in small groups.',
                'file_path' => 'gallery/arabic-classes/conversation-practice.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 198765,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/arabic-classes/thumbnails/conversation-practice.jpg',
                'alt_text' => 'Students practicing Arabic conversation',
                'caption' => 'Building confidence through practical conversation practice.',
                'tags' => ['arabic', 'conversation', 'practice', 'groups'],
                'sort_order' => 2,
                'is_featured' => false,
                'is_public' => true,
            ],

            // Community Events Album
            [
                'gallery_album_id' => $createdAlbums[3]->id,
                'title' => 'Community Iftar Gathering',
                'description' => 'Annual community Iftar bringing together families and friends.',
                'file_path' => 'gallery/community-events/community-iftar.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 456123,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/community-events/thumbnails/community-iftar.jpg',
                'alt_text' => 'Community Iftar gathering',
                'caption' => 'A beautiful evening of unity and fellowship.',
                'tags' => ['community', 'iftar', 'gathering', 'unity'],
                'sort_order' => 1,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[3]->id,
                'title' => 'Eid Celebration',
                'description' => 'Joyous Eid celebration with traditional food and activities.',
                'file_path' => 'gallery/community-events/eid-celebration.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 345678,
                'dimensions' => ['width' => 1920, 'height' => 1280],
                'thumbnail_path' => 'gallery/community-events/thumbnails/eid-celebration.jpg',
                'alt_text' => 'Eid celebration at Akuru Institute',
                'caption' => 'Celebrating the blessed occasion of Eid with our community.',
                'tags' => ['eid', 'celebration', 'community', 'festival'],
                'sort_order' => 2,
                'is_featured' => false,
                'is_public' => true,
            ],

            // Graduation Ceremony Album
            [
                'gallery_album_id' => $createdAlbums[4]->id,
                'title' => 'Graduation Procession',
                'description' => 'Graduates walking in procession during the commencement ceremony.',
                'file_path' => 'gallery/graduation-2024/graduation-procession.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 567890,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/graduation-2024/thumbnails/graduation-procession.jpg',
                'alt_text' => 'Graduation procession ceremony',
                'caption' => 'A proud moment as our graduates receive their certificates.',
                'tags' => ['graduation', 'ceremony', 'graduates', 'achievement'],
                'sort_order' => 1,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[4]->id,
                'title' => 'Certificate Presentation',
                'description' => 'Graduates receiving their certificates from the principal.',
                'file_path' => 'gallery/graduation-2024/certificate-presentation.mp4',
                'file_type' => 'video',
                'mime_type' => 'video/mp4',
                'file_size' => 25165824,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/graduation-2024/thumbnails/certificate-presentation.jpg',
                'alt_text' => 'Certificate presentation ceremony',
                'caption' => 'Recognition of years of hard work and dedication.',
                'tags' => ['graduation', 'certificates', 'presentation', 'recognition'],
                'sort_order' => 2,
                'is_featured' => true,
                'is_public' => true,
            ],

            // Islamic Workshops Album
            [
                'gallery_album_id' => $createdAlbums[5]->id,
                'title' => 'Tajweed Workshop',
                'description' => 'Interactive workshop on proper Quran recitation techniques.',
                'file_path' => 'gallery/islamic-workshops/tajweed-workshop.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 234567,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/islamic-workshops/thumbnails/tajweed-workshop.jpg',
                'alt_text' => 'Tajweed workshop session',
                'caption' => 'Learning the art of beautiful Quran recitation.',
                'tags' => ['tajweed', 'workshop', 'quran', 'recitation'],
                'sort_order' => 1,
                'is_featured' => false,
                'is_public' => true,
            ],

            // Campus Facilities Album
            [
                'gallery_album_id' => $createdAlbums[6]->id,
                'title' => 'Main Prayer Hall',
                'description' => 'Our beautiful main prayer hall where students and community gather for prayers.',
                'file_path' => 'gallery/campus-facilities/main-prayer-hall.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 456789,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/campus-facilities/thumbnails/main-prayer-hall.jpg',
                'alt_text' => 'Main prayer hall at Akuru Institute',
                'caption' => 'A peaceful space for worship and reflection.',
                'tags' => ['prayer hall', 'facilities', 'worship', 'campus'],
                'sort_order' => 1,
                'is_featured' => true,
                'is_public' => true,
            ],
            [
                'gallery_album_id' => $createdAlbums[6]->id,
                'title' => 'Library and Study Area',
                'description' => 'Well-equipped library with Islamic books and quiet study spaces.',
                'file_path' => 'gallery/campus-facilities/library-study-area.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 345678,
                'dimensions' => ['width' => 1920, 'height' => 1280],
                'thumbnail_path' => 'gallery/campus-facilities/thumbnails/library-study-area.jpg',
                'alt_text' => 'Library and study area',
                'caption' => 'A quiet space for learning and research.',
                'tags' => ['library', 'study', 'books', 'learning'],
                'sort_order' => 2,
                'is_featured' => false,
                'is_public' => true,
            ],

            // Teacher Training Album
            [
                'gallery_album_id' => $createdAlbums[7]->id,
                'title' => 'Professional Development Session',
                'description' => 'Teachers participating in professional development workshops.',
                'file_path' => 'gallery/teacher-training/professional-development.jpg',
                'file_type' => 'image',
                'mime_type' => 'image/jpeg',
                'file_size' => 234567,
                'dimensions' => ['width' => 1920, 'height' => 1080],
                'thumbnail_path' => 'gallery/teacher-training/thumbnails/professional-development.jpg',
                'alt_text' => 'Teacher professional development session',
                'caption' => 'Continuous learning and improvement for our teaching staff.',
                'tags' => ['teachers', 'training', 'professional development', 'education'],
                'sort_order' => 1,
                'is_featured' => false,
                'is_public' => true,
            ],
        ];

        foreach ($galleryItems as $item) {
            GalleryItem::create($item);
        }

        // Update album item counts
        foreach ($createdAlbums as $album) {
            $album->updateItemCount();
        }
    }
}