<?php

/**
 * Every place the app renders HTML without escaping it — `{!! !!}` in a Blade
 * view, `dangerouslySetInnerHTML` in a React page — and **what sanitises the
 * value on the way in**, because that, not the render site, is what makes it
 * safe.
 *
 * See `tests/Architecture/RawHtmlRendersAreDeclaredTest.php`. **This list may
 * only shrink**: the test fails on a new sink and on a stale entry alike.
 *
 * ## Why one entry per sink, and not per file as this gate used to be
 *
 * The gate existed before this list did, keyed by **file**, with one
 * justification each. `documents/course-certificate.blade.php` has two sinks of
 * different kinds — an authored template body and a QR SVG we generate — and
 * its single declaration read *"system-generated: template body and QR svg"*.
 * True of the QR. False of the body, which `course_creator` writes and which
 * was sanitised with a `strip_tags` tag allowlist that keeps every attribute.
 *
 * So the gate was green, the declaration was the thing asserting safety, and
 * the declaration was wrong. One entry per sink leaves nowhere for a second
 * kind of content to shelter behind the first one's reason.
 *
 * ## Why keyed by expression rather than line number
 *
 * A line number breaks every time somebody edits the line above, which trains
 * people to re-point the baseline without reading it — the opposite of the
 * point. The expression is stable under that and still unique: all 25 sinks
 * differ.
 *
 * ## The three kinds
 *
 *  - **Sanitised on write** — an author's rich text, cleaned by
 *    `App\Support\Html\HtmlSanitizer` before it reaches the database. Each
 *    entry **names the Action or controller** rather than asserting "it's
 *    fine", because a claim cannot be checked by the next reader and a file
 *    name can.
 *  - **Generated by us** — a QR SVG, a barcode, a JSON-LD payload. Not user
 *    input at all.
 *  - **Escaped at the sink instead** — nothing here, deliberately. A value with
 *    no HTML in it belongs in `{{ }}`, and three such sinks were converted
 *    rather than listed (`e-learning/show.blade.php` subject descriptions,
 *    which the old file-level list carried as "no write path: legacy screen,
 *    seed-only columns" — true, and a weaker guarantee than simply escaping
 *    them).
 *
 * @return array<string, string>
 */
return [
    // --- CMS bodies: sanitised in the admin controllers ---------------------
    'admin/public-site/pages/show.blade.php :: $page->body' => 'PageController sanitises `body` with HtmlSanitizer::PROFILE_CMS on both store and update.',
    'public/page/show.blade.php :: $page->body' => 'Same column, same write path as the admin preview above.',
    'public/about/index.blade.php :: $page->body' => 'Same `pages.body` column and the same sanitised write path.',
    'public/courses/show.blade.php :: $course->body' => 'Admin PublicSite CourseController sanitises `body` with PROFILE_CMS on store and update.',

    // --- Posts: one write path for news, articles and research --------------
    'public/articles/show.blade.php :: $post->body' => 'SaveResearchPostAction is the only writer of `posts.body` and cleans it with PROFILE_CMS. News and articles read the same model.',
    'public/news/show.blade.php :: $post->body' => 'As above — the same column and the same single writer.',
    "public/research/show.blade.php :: \$item['body']" => 'As above, surfaced through PresentResearchPostAction.',

    // --- Events -------------------------------------------------------------
    'public/events/show.blade.php :: $event->description' => 'SaveEventAction cleans `description` with PROFILE_CMS.',
    'public/events/show.blade.php :: $event->requirements' => 'SaveEventAction cleans `requirements` the same way.',

    // --- Library: the item body, and the pages sliced from it ---------------
    "public/library/show.blade.php :: \$item['body']" => 'SaveLibraryItemAction cleans each part of `body` with PROFILE_CMS. The lowest-privilege authored HTML in the app: any authed user may apply to be a writer.',
    "public/library/reader.blade.php :: \$reader['content']" => 'The reader renders `library_item_pages.content`, which SyncLibraryItemPagesAction slices from the already-sanitised `body`. Nothing else writes those rows.',

    // --- Documents ----------------------------------------------------------
    'documents/course-certificate.blade.php :: $body_html' => 'SaveCertificateTemplateAction cleans the template body with PROFILE_CMS. **This was the one live hole**: it used strip_tags with a tag allowlist, which keeps every attribute, so `<p onmouseover>` reached the rendered certificate. Fixed 2026-09-14; StripTagsIsNotASanitiserTest is the gate that stops it recurring.',
    'documents/course-certificate.blade.php :: $qr' => 'StudentNumberQr::svg() — an SVG we generate from a verification URL, not author input.',
    'documents/id-card.blade.php :: $qr' => 'The same generated QR SVG.',

    // --- Generated by us ----------------------------------------------------
    'public/partials/json_ld.blade.php :: json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP)' => 'JSON_HEX_TAG | JSON_HEX_AMP is exactly what makes a payload safe inside a <script> element: `</script>` in a string cannot close the tag.',

    // --- React: dangerouslySetInnerHTML -------------------------------------
    // The Blade sweep would have missed these entirely, and the new UI is
    // React. Four sites, all checked against their write paths.
    "Pages/Courses/Player/Show.jsx :: wrapHtml(block.data?.html || '', glossary)" => 'ValidateContentBlockDataAction cleans block HTML with PROFILE_LESSON. `wrapHtml` then wraps glossary matches — it interpolates only `item.id` (an integer) and `$1` (text from the already-sanitised HTML), and escapes the label before building the RegExp, so it adds no new input.',
    'Pages/Library/Review.jsx :: item.body' => 'The reviewer previews the same `library_items.body` the public page renders, and SaveLibraryItemAction cleans it on save — so a submission is sanitised before a reviewer ever opens it, not on approval.',
    'Pages/Circulation/Labels.jsx :: label.barcode' => 'Circulation\\Support\\Code39 — an SVG we generate from an accession number.',
    'Pages/Circulation/BorrowerCards.jsx :: card.barcode' => 'The same generated Code39 SVG.',
    'Pages/Academics/Gate/PrintCards.jsx :: svg' => 'The `qrcode` package\'s SVG of a gate card code — `AKG:` and a 16-character token IssueGateCardsAction draws from a fixed alphabet; no author input reaches it.',
];
