<?php

// CLAUDE.md Conventions: "All screens trilingual-ready (EN/DV/AR)".
// English UI-string keys with no Dhivehi AND no Arabic entry in resources/lang.
// Baseline may only shrink when strings are translated — never grow.
// Baseline count: 126

return [
    'public.Access opens as soon as the bank confirms your payment.',
    'public.All Enrollment',
    'public.All Statuses',
    'public.All categories',
    'public.All types',
    'public.Amount',
    'public.Apply Filters',
    'public.Apply now and begin your Islamic education journey',
    'public.Audience',
    'public.Auditorium',
    'public.Balance',
    'public.Bank confirmation can take a moment. Refresh this page shortly — access is granted as soon as the bank confirms.',
    'public.Bookmark this page',
    'public.Bookmarks',
    'public.Books, articles and research from Akuru Institute',
    'public.Buy for',
    'public.Category',
    'public.Choose from our comprehensive range of Islamic education programs',
    'public.Clear All',
    'public.Clear Filters',
    'public.Coming soon',
    'public.Complete Quran memorization program',
    'public.Completed',
    'public.Comprehensive Islamic education for all ages',
    'public.Confirming your payment…',
    'public.Congratulations to all participants...',
    'public.Continue',
    'public.Continue reading',
    'public.Course Categories',
    'public.Course Statistics',
    'public.Default',
    'public.Discount code',
    'public.Enroll',
    'public.Enroll in this course',
    'public.Enroll with OTP verification and payment',
    'public.Enrollment',
    'public.Enrollment Open',
    'public.Event Details',
    'public.Featured',
    'public.Featured First',
    'public.Featured Only',
    'public.Islamic Studies Program',
    'public.Join thousands of students who have chosen Akuru Institute for their Islamic education',
    'public.Language',
    'public.Learn Arabic from basics to fluency',
    'public.Level',
    'public.Login to read',
    'public.Main Campus',
    'public.Mixed',
    'public.Monday',
    'public.Need More Information?',
    'public.New Academic Year Starts',
    'public.Next',
    'public.No Courses Found',
    'public.No bookmarks yet.',
    'public.No purchases yet.',
    'public.No wallet activity yet.',
    'public.Nothing in progress — find something in the library.',
    'public.Nothing in the library matches your search yet.',
    'public.One flow',
    'public.Open House Day',
    'public.Open for Enrollment',
    'public.Or submit an inquiry',
    'public.Our Courses',
    'public.Page',
    'public.Pay with wallet',
    'public.Payment confirmed',
    'public.Please try different filters or check back later',
    'public.Previous',
    'public.Price: High to Low',
    'public.Price: Low to High',
    'public.Purchases',
    'public.Qualified Teachers',
    'public.Quran Competition Results',
    'public.Quran Recitation Competition',
    'public.Read again',
    'public.Read online',
    'public.Ready to Start Your Journey?',
    'public.Redeem gift card',
    'public.Refresh',
    'public.Register Now',
    'public.Registration',
    'public.Registration is now open for the new academic year...',
    'public.Remove bookmark',
    'public.Requirements',
    'public.Search courses...',
    'public.Search the library',
    'public.Sign in',
    'public.Sign in to read this item for free.',
    'public.Sort By',
    'public.Source',
    'public.Start Date',
    'public.Starting Soon',
    'public.Status',
    'public.Students Enrolled',
    'public.Submit an inquiry',
    'public.Sunday',
    'public.Thank you',
    'public.This item has no reader pages yet.',
    'public.This item is not yet available for online reading.',
    'public.Thursday',
    'public.Title A-Z',
    'public.Total Courses',
    'public.Transactions',
    'public.Tuesday',
    'public.Type',
    'public.Verify via OTP',
    'public.View All Events',
    'public.View All News',
    'public.View Details',
    'public.Waitlist only',
    'public.Wednesday',
    'public.WhatsApp',
    'public.Your access is ready.',
    'public.and pay to complete',
    'public.article',
    'public.book',
    'public.complete enrollment',
    'public.contact_for_more_info',
    'public.course_material',
    'public.pages',
    'public.pay to complete',
    'public.register',
    'public.registration_required_message',
    'public.research',
    'public.seats available',
];
