<?php

// CLAUDE.md Conventions: "All screens trilingual-ready (EN/DV/AR)".
// English UI-string keys with no Dhivehi AND no Arabic entry in resources/lang.
// Baseline may only shrink when strings are translated — never grow.
// Baseline count: 200

return [
    'common.assignment_completion',
    'common.avg_accuracy',
    'common.completed_surahs',
    'common.current_prayer',
    'common.from_last_month',
    'common.growth_rate',
    'common.last_month',
    'common.new_assignments',
    'common.new_students',
    'common.next_prayer',
    'common.quran_progress_stats',
    'common.quran_progress_updates',
    'common.recent_activities',
    'common.special_islamic_days',
    'common.student_growth',
    'common.upcoming_assignments',
    'common.upcoming_classes',
    'common.upcoming_events',
    'public.Access opens as soon as the bank confirms your payment.',
    'public.Address',
    'public.Admission Process',
    'public.All Enrollment',
    'public.All Statuses',
    'public.All categories',
    'public.All types',
    'public.Amount',
    'public.Apply Filters',
    'public.Apply for Admission',
    'public.Apply now and begin your Islamic education journey',
    'public.Arabic Language Courses',
    'public.Audience',
    'public.Auditorium',
    'public.Back to Home',
    'public.Balance',
    'public.Bank confirmation can take a moment. Refresh this page shortly — access is granted as soon as the bank confirms.',
    'public.Bookmark this page',
    'public.Bookmarks',
    'public.Books, articles and research from Akuru Institute',
    'public.Buy for',
    'public.Category',
    'public.Choose from our comprehensive range of Islamic education programs',
    'public.Clear All',
    'public.Clear Filters',
    'public.Coming soon',
    'public.Complete Quran memorization program',
    'public.Completed',
    'public.Comprehensive Islamic education for all ages',
    'public.Confirming your payment…',
    'public.Congratulations to all participants...',
    'public.Contact Support',
    'public.Continue',
    'public.Continue reading',
    'public.Course',
    'public.Course Categories',
    'public.Course Statistics',
    'public.Course of Interest',
    'public.Default',
    'public.Discount code',
    'public.Enroll',
    'public.Enroll in this course',
    'public.Enroll with OTP verification and payment',
    'public.Enrollment',
    'public.Enrollment Open',
    'public.Event Details',
    'public.Featured',
    'public.Featured First',
    'public.Featured Only',
    'public.Free',
    'public.Friday',
    'public.Get Help',
    'public.Go Home',
    'public.How did you hear about us?',
    'public.Islamic Studies Program',
    'public.Join thousands of students who have chosen Akuru Institute for their Islamic education',
    'public.Language',
    'public.Learn Arabic from basics to fluency',
    'public.Learn Arabic from beginner to advanced levels',
    'public.Learn Quran with Expert Teachers',
    'public.Learn Quran, Arabic, and Islamic Studies in the Maldives',
    'public.Level',
    'public.Library',
    'public.Login to read',
    'public.Main Campus',
    'public.Master the Holy Quran with our qualified instructors',
    'public.Mixed',
    'public.Monday',
    'public.My Library',
    'public.My Wallet',
    'public.Need Help?',
    'public.Need More Information?',
    'public.Need help?',
    'public.New Academic Year Starts',
    'public.Next',
    'public.No Courses Found',
    'public.No bookmarks yet.',
    'public.No purchases yet.',
    'public.No wallet activity yet.',
    'public.Nothing in progress — find something in the library.',
    'public.Nothing in the library matches your search yet.',
    'public.Office Hours',
    'public.One flow',
    'public.Open House Day',
    'public.Open for Enrollment',
    'public.Or submit an inquiry',
    'public.Other',
    'public.Our Courses',
    'public.Page',
    'public.Page Not Found',
    'public.Pay with wallet',
    'public.Payment confirmed',
    'public.Personal Info',
    'public.Please try different filters or check back later',
    'public.Popular Pages',
    'public.Previous',
    'public.Price: High to Low',
    'public.Price: Low to High',
    'public.Purchases',
    'public.Qualified Teachers',
    'public.Quran Competition Results',
    'public.Quran Recitation Competition',
    'public.Read again',
    'public.Read online',
    'public.Ready to Start Your Journey?',
    'public.Redeem gift card',
    'public.Refresh',
    'public.Register Now',
    'public.Registration',
    'public.Registration is now open for the new academic year...',
    'public.Remove bookmark',
    'public.Requirements',
    'public.Review',
    'public.Saturday',
    'public.Search courses...',
    'public.Search the library',
    'public.Select a course',
    'public.Send us a Message',
    'public.Server Error',
    'public.Sign in',
    'public.Sign in to buy and read this item.',
    'public.Sign in to read this item for free.',
    'public.Social Media',
    'public.Something went wrong on our end. Please try again later.',
    'public.Sort By',
    'public.Source',
    'public.Start Date',
    'public.Starting Soon',
    'public.Status',
    'public.Still having issues?',
    'public.Students Enrolled',
    'public.Submit an inquiry',
    'public.Sunday',
    'public.Sunday - Thursday',
    'public.Thank You!',
    'public.Thank you',
    'public.The page you are looking for could not be found.',
    'public.This item has no reader pages yet.',
    'public.This item is not yet available for online reading.',
    'public.Thursday',
    'public.Title A-Z',
    'public.Total Courses',
    'public.Transactions',
    'public.Try Again',
    'public.Tuesday',
    'public.Type',
    'public.Verify via OTP',
    'public.View All Events',
    'public.View All News',
    'public.View Details',
    'public.View larger map',
    'public.Waitlist only',
    'public.Website',
    'public.Wednesday',
    'public.What happens next?',
    'public.WhatsApp',
    'public.Your access is ready.',
    'public.admission_description',
    'public.admission_message_placeholder',
    'public.admission_next_step1',
    'public.admission_next_step2',
    'public.admission_next_step3',
    'public.admission_submitted_successfully',
    'public.and pay to complete',
    'public.article',
    'public.book',
    'public.complete enrollment',
    'public.contact_description',
    'public.contact_for_more_info',
    'public.contact_message_placeholder',
    'public.contact_us_for_questions',
    'public.course_material',
    'public.min read',
    'public.pages',
    'public.pay to complete',
    'public.register',
    'public.registration_required_message',
    'public.research',
    'public.seats available',
    'public.step1_description',
    'public.step2_description',
    'public.step3_description',
];
