<?php

// CLAUDE.md Conventions: "All screens trilingual-ready (EN/DV/AR)".
// English UI-string keys with no Dhivehi AND no Arabic entry in resources/lang.
// Baseline may only shrink when strings are translated — never grow.
// Baseline count: 91

return [
    'public.Access opens as soon as the bank confirms your payment.',
    'public.All categories',
    'public.All types',
    'public.Amount',
    'public.Audience',
    'public.Auditorium',
    'public.Balance',
    'public.Bank confirmation can take a moment. Refresh this page shortly — access is granted as soon as the bank confirms.',
    'public.Bookmark this page',
    'public.Bookmarks',
    'public.Books, articles and research from Akuru Institute',
    'public.Buy for',
    'public.Choose from our comprehensive range of Islamic education programs',
    'public.Coming soon',
    'public.Complete Quran memorization program',
    'public.Completed',
    'public.Comprehensive Islamic education for all ages',
    'public.Confirming your payment…',
    'public.Congratulations to all participants...',
    'public.Continue',
    'public.Continue reading',
    'public.Discount code',
    'public.Enroll',
    'public.Enroll with OTP verification and payment',
    'public.Event Details',
    'public.Islamic Studies Program',
    'public.Join thousands of students who have chosen Akuru Institute for their Islamic education',
    'public.Learn Arabic from basics to fluency',
    'public.Login to read',
    'public.Main Campus',
    'public.Monday',
    'public.Need More Information?',
    'public.New Academic Year Starts',
    'public.Next',
    'public.No bookmarks yet.',
    'public.No purchases yet.',
    'public.No wallet activity yet.',
    'public.Nothing in progress — find something in the library.',
    'public.Nothing in the library matches your search yet.',
    'public.One flow',
    'public.Open House Day',
    'public.Page',
    'public.Pay with wallet',
    'public.Payment confirmed',
    'public.Previous',
    'public.Purchases',
    'public.Qualified Teachers',
    'public.Quran Competition Results',
    'public.Quran Recitation Competition',
    'public.Read again',
    'public.Read online',
    'public.Ready to Start Your Journey?',
    'public.Redeem gift card',
    'public.Refresh',
    'public.Register Now',
    'public.Registration',
    'public.Registration is now open for the new academic year...',
    'public.Remove bookmark',
    'public.Requirements',
    'public.Search the library',
    'public.Sign in',
    'public.Sign in to read this item for free.',
    'public.Source',
    'public.Students Enrolled',
    'public.Sunday',
    'public.Thank you',
    'public.This item has no reader pages yet.',
    'public.This item is not yet available for online reading.',
    'public.Thursday',
    'public.Transactions',
    'public.Tuesday',
    'public.Type',
    'public.Verify via OTP',
    'public.View All Events',
    'public.View All News',
    'public.Waitlist only',
    'public.Wednesday',
    'public.WhatsApp',
    'public.Your access is ready.',
    'public.and pay to complete',
    'public.article',
    'public.book',
    'public.complete enrollment',
    'public.contact_for_more_info',
    'public.course_material',
    'public.pages',
    'public.pay to complete',
    'public.register',
    'public.registration_required_message',
    'public.research',
    'public.seats available',
];
