<?php

/**
 * Eloquent morph-map aliases (alias => current FQCN).
 *
 * Registered via MorphMapServiceProvider with Relation::morphMap() (non-enforcing).
 * Reuses aliases from config/domain-models.php where those classes appear.
 * Legacy App\\Models\\* → alias rewrites live in App\\Support\\MorphMap (backfill only).
 */

return [
    'absence_note' => \App\Domains\Academics\Models\AbsenceNote::class,
    'academic_year' => \App\Domains\Academics\Models\AcademicYear::class,
    'admission_application' => \App\Domains\Admissions\Models\AdmissionApplication::class,
    'announcement' => \App\Domains\Academics\Models\Announcement::class,
    'assignment' => \App\Domains\Academics\Legacy\Models\Assignment::class,
    'assignment_submission' => \App\Domains\Academics\Legacy\Models\AssignmentSubmission::class,
    'attendance' => \App\Domains\Academics\Models\Attendance::class,
    'calendar_day' => \App\Domains\Academics\Models\CalendarDay::class,
    'class_room' => \App\Domains\Academics\Models\ClassRoom::class,
    'class_student' => \App\Domains\Academics\Models\ClassStudent::class,
    'consent' => \App\Domains\People\Models\Consent::class,
    'contact_inquiry' => \App\Domains\Website\Models\ContactInquiry::class,
    'contact_message' => \App\Domains\Website\Models\ContactMessage::class,
    'custom_field_definition' => \App\Domains\People\Models\CustomFieldDefinition::class,
    'custom_field_value' => \App\Domains\People\Models\CustomFieldValue::class,
    'course' => \App\Domains\Courses\Models\Course::class,
    'course_category' => \App\Domains\Courses\Models\CourseCategory::class,
    'course_enrollment' => \App\Domains\Courses\Models\CourseEnrollment::class,
    'course_plan' => \App\Domains\Academics\Models\CoursePlan::class,
    'dashboard_analytics' => \App\Domains\Settings\Models\DashboardAnalytics::class,
    'device' => \App\Domains\Notifications\Models\Device::class,
    'document' => \App\Domains\Media\Models\Document::class,
    'emergency_contact' => \App\Domains\People\Models\EmergencyContact::class,
    'event' => \App\Domains\Website\Models\Event::class,
    'event_registration' => \App\Domains\Website\Models\EventRegistration::class,
    'faq' => \App\Domains\Website\Models\Faq::class,
    'fee_item' => \App\Domains\Finance\Models\FeeItem::class,
    'gallery_album' => \App\Domains\Website\Models\GalleryAlbum::class,
    'gallery_item' => \App\Domains\Website\Models\GalleryItem::class,
    'grade' => \App\Domains\Academics\Models\Grade::class,
    'hero_banner' => \App\Domains\Website\Models\HeroBanner::class,
    'hifz_assignment' => \App\Domains\Hifz\Models\HifzAssignment::class,
    'hifz_enrollment' => \App\Domains\Hifz\Models\HifzEnrollment::class,
    'hifz_milestone' => \App\Domains\Hifz\Models\HifzMilestone::class,
    'hifz_mistake' => \App\Domains\Hifz\Models\HifzMistake::class,
    'hifz_program' => \App\Domains\Hifz\Models\HifzProgram::class,
    'hifz_session' => \App\Domains\Hifz\Models\HifzSession::class,
    'hifz_session_record' => \App\Domains\Hifz\Models\HifzSessionRecord::class,
    'inquiry_type' => \App\Domains\Website\Models\InquiryType::class,
    'instructor' => \App\Domains\HR\Models\Instructor::class,
    'invoice' => \App\Domains\Finance\Models\Invoice::class,
    'invoice_line' => \App\Domains\Finance\Models\InvoiceLine::class,
    'lesson_log' => \App\Domains\Academics\Models\LessonLog::class,
    'media_gallery' => \App\Domains\Media\Models\MediaGallery::class,
    'media_item' => \App\Domains\Media\Models\MediaItem::class,
    'message' => \App\Domains\Notifications\Models\Message::class,
    'notification' => \App\Domains\Notifications\Models\Notification::class,
    'notification_template' => \App\Domains\Notifications\Models\NotificationTemplate::class,
    'otp' => \App\Domains\Identity\Models\Otp::class,
    'page' => \App\Domains\Website\Models\Page::class,
    'parent_guardian' => \App\Domains\People\Models\ParentGuardian::class,
    'payment' => \App\Domains\Finance\Models\Payment::class,
    'payment_item' => \App\Domains\Finance\Models\PaymentItem::class,
    'period' => \App\Domains\Academics\Models\Period::class,
    'plan_topic' => \App\Domains\Academics\Models\PlanTopic::class,
    'post' => \App\Domains\Website\Models\Post::class,
    'post_category' => \App\Domains\Website\Models\PostCategory::class,
    'quiz' => \App\Domains\Academics\Legacy\Models\Quiz::class,
    'quiz_attempt' => \App\Domains\Academics\Legacy\Models\QuizAttempt::class,
    'quiz_question' => \App\Domains\Academics\Legacy\Models\QuizQuestion::class,
    'quran_ayah' => \App\Domains\Hifz\Models\QuranAyah::class,
    'quran_mushaf' => \App\Domains\Hifz\Models\QuranMushaf::class,
    'quran_page' => \App\Domains\Hifz\Models\QuranPage::class,
    'quran_progress' => \App\Domains\Hifz\Models\QuranProgress::class,
    'quran_word' => \App\Domains\Hifz\Models\QuranWord::class,
    'quran_word_position' => \App\Domains\Hifz\Models\QuranWordPosition::class,
    'recitation_practice' => \App\Domains\Hifz\Models\RecitationPractice::class,
    'registration_flow' => \App\Domains\Admissions\Models\RegistrationFlow::class,
    'registration_student' => \App\Domains\People\Models\RegistrationStudent::class,
    'report' => \App\Domains\Settings\Models\Report::class,
    'room' => \App\Domains\Academics\Models\Room::class,
    'room_booking' => \App\Domains\Academics\Models\RoomBooking::class,
    'school' => \App\Domains\Settings\Models\School::class,
    'setting' => \App\Domains\Settings\Models\Setting::class,
    'staff_profile' => \App\Domains\People\Models\StaffProfile::class,
    'staff_qualification' => \App\Domains\People\Models\StaffQualification::class,
    'student' => \App\Domains\People\Models\Student::class,
    'student_status_history' => \App\Domains\People\Models\StudentStatusHistory::class,
    'subject' => \App\Domains\Academics\Models\Subject::class,
    'substitution_assignment' => \App\Domains\Academics\Models\SubstitutionAssignment::class,
    'substitution_request' => \App\Domains\Academics\Models\SubstitutionRequest::class,
    'surah' => \App\Domains\Hifz\Models\Surah::class,
    'system_metric' => \App\Domains\Settings\Models\SystemMetric::class,
    'tajweed_feedback' => \App\Domains\Hifz\Models\TajweedFeedback::class,
    'teacher' => \App\Domains\People\Models\Teacher::class,
    'teacher_absence' => \App\Domains\Academics\Models\TeacherAbsence::class,
    'term' => \App\Domains\Academics\Models\Term::class,
    'testimonial' => \App\Domains\Website\Models\Testimonial::class,
    'timetable' => \App\Domains\Academics\Models\Timetable::class,
    'user' => \App\Domains\Identity\Models\User::class,
    'user_activity' => \App\Domains\Settings\Models\UserActivity::class,
    'user_contact' => \App\Domains\Identity\Models\UserContact::class,
    'user_notification' => \App\Domains\Notifications\Models\UserNotification::class,
];
